# Generated by Django 3.2.8 on 2021-10-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('username', 'password')},
        ),
    ]
